### ISSUE TITLE
请问正则如何使用

### ISSUE THREAD

**Issue by transtone** [react-component/form-validation#12]
validation没有正则的例子，不知道怎么用，这样不生效：
rules={[{ type:"regexp", pattern:"^(1[3-8]\d{9})$", required: true }]}

**Comment by benjycui** [comment]
form-validation 内部是用 async-validator 进行校验的，所以相关规则配置请看：https://github.com/yiminghe/async-validator

**Comment by yiminghe** [comment]
http://react-component.github.io/form-validation/examples/form.html

搜索 pattern

**Comment by transtone** [comment]
谢谢，一直去找regexp的例子了，漏掉了pattern。
