### ISSUE TITLE
require('../')? Module package name?

### ISSUE THREAD

**Issue by albertchan** [react-component/form-validation#14]
I'm having issues importing the package in my React.js app. I've tried the following but none of them worked. I keep getting an error similar to `Uncaught Error: Cannot find module "rc-form-validation"`.

`Validation = require('rc-form-validation');`
`Validation = require('../');`

I'm currently using Brunch to compile my scripts. Any ideas?

**Comment by simaQ** [comment]
Did the rc-form-validation module been installed in your project?  

`npm install rc-form-validation --save`

**Comment by albertchan** [comment]
After some investigating, no. I have listed `rc-form-validation` as a dependency but Brunch can't seem to join the module into my vendors.js file. A snippet of my brunch-config.js is below.

```
javascripts: {
  joinTo: {
    'js/vendors.js': [
      /^(bower_components)/,
      'node_modules/rc-form-validation/lib/index.js'
    ],
    'js/app.js': /^app/
  }
}
```

Not sure how I can hack the module into my Brunch workflow though...

**Comment by yiminghe** [comment]
try webpack
