### ISSUE TITLE
type url 验证失败

### ISSUE THREAD

**Issue by noyobo** [react-component/form-validation#15]
https://github.com/noyobo/form-validation/commit/255a13e224fa2804429c85c67ea7e07ace3bc8a5

新增测试用例

运行结果如下

https://travis-ci.org/noyobo/form-validation/jobs/90097814

**Comment by yiminghe** [comment]
https://github.com/yiminghe/async-validator/commit/a0d95675ee50956fe4f9e7a4c9a5a42551c28efc
