### ISSUE TITLE
how did the error message populate to the state variable? 

### ISSUE THREAD

**Issue by yubozhao** [react-component/form-validation#20]
as in the example/form.js.  I couldnt duplicated or figure out how did the error message populated to the state variable.

any tips?

**Comment by yiminghe** [comment]
Could you try http://react-component.github.io/form/, this project will be obsolete

**Comment by yubozhao** [comment]
Sweet thx. 

Bo




On Thu, Jan 7, 2016 at 7:03 PM -0800, "yiminghe" <notifications@github.com> wrote:












Could you try http://react-component.github.io/form/, this project will be obsolete
