### ISSUE TITLE
message信息可以自定义么？

### ISSUE THREAD

**Issue by lyd600lty** [react-component/form-validation#21]
message信息里可以添加dom么？

**Comment by benjycui** [comment]
问题就不能描述清楚点？麻烦先读下这个 http://doc.zengrong.net/smart-questions/cn.html

**Comment by lyd600lty** [comment]
感谢分享
错误提示的信息可以自定义dom么？现在传入message字段的只是文字。

**Comment by benjycui** [comment]
form-validation 的校验是基于 async-validator 的，而目前 async-validator 不支持传入 DOM，但可以自行把返回的 Errors' messages 包装成 DOM。

@yiminghe 把 form-validation 标为 deprecated 并把用户导向 rc-form?
