### ISSUE TITLE
async-validator 版本依赖声明兼容问题

### ISSUE THREAD

**Issue by renxia** [react-component/form-validation#23]
form-validation 对 async-validator 的依赖引用限制在 1.3.x

https://github.com/react-component/form-validation/blob/master/package.json#L56

rc-form 中对其依赖为 1.x

https://github.com/react-component/form/blob/master/package.json#L64

然而 async-validator  当前版本为 1.5.1

这导致了  async-validator  会被同时加载两个不同版本。请更新依赖关系！

**Comment by benjycui** [comment]
用了 rc-form，为何还要用 rc-form-validation。。。都替换为 rc-form 吧，毕竟 rc-form-validation 已经废弃

**Comment by renxia** [comment]
我这里是参考组件示例使用

```
import { Menu, Dropdown } from 'antd';
```
这种方式加载的，那么所有的依赖都会被分析到。0.12.12 版本是存在这个问题的

看了下仓库中最近的修改，是已经移除这个组件了，希望能尽快的更新到 npm 啊~
https://github.com/ant-design/ant-design/commit/596fbc80d5de8bdfee0fd93bde327b20225ac4c8
