### ISSUE TITLE
`this.props.children` 的值异常

### ISSUE THREAD

**Issue by benjycui** [react-component/form-validation#8]
定义一个 `React.Component`，如：
```jsx
var Test = React.createClass({
  render() {
    console.log(this.props.children);
    return this.props.children;
  }
});
```

将其置于 `Validation` 内：
```xml
<Validation>
  <Test><input type='text' /></Test>
</Validation>
```

`console.log`  输出的值预期为：`ReactElement`，但实际为 `{'.0': ReactElement, ...}`

`ReactElement` 被包裹起来了？

**Comment by benjycui** [comment]
排查后觉得是 `React.Children.map` 的问题，See: https://github.com/facebook/react/issues/4410

**Comment by yiminghe** [comment]
need to skip CustomComponent, when process element inside Validator.

CustomComponent has to expose onChange handler

**Comment by benjycui** [comment]
What if `Validator` inside a `CustomComponent`, just like this:

```xml
<Validation>
  <CustomComponent>
    <Validator>
      <input type='text' />
    </Validator>
  </CustomComponent>
</Validation>
```
