### ISSUE TITLE
Proposal: make `Validator` handle its own `status`.

### ISSUE THREAD

**Issue by benjycui** [react-component/form-validation#9]
With current version, user must create a component [to hold all the `Validator`s' statuses](https://github.com/react-component/form-validation/blob/master/examples/form.js#L30).

I am not sure whether it is designed to be this or I misunderstand it.

But IMHO, we can make a little enhancement to make `Validator` handle its own `status`. So, users will feel more convenient. 

If you are interested in this proposal, I will implement it in next week.

Ping @yiminghe

**Comment by yiminghe** [comment]
this is form business data, user need this to submit data or show error.

validation components should be functional as pure as possible (aka. no state...)

**Comment by benjycui** [comment]
Gotcha！
